# Generated by Django 4.1.7 on 2023-04-25 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ziria", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("currency", models.CharField(max_length=3)),
                ("country", models.CharField(max_length=3)),
                ("payments_enabled", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "stores",
            },
        ),
    ]
