# Generated by Django 4.1.7 on 2023-04-25 17:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ziria", "0005_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.TextField()),
                ("is_base_variant", models.BooleanField(default=True)),
                ("position", models.IntegerField(blank=True, default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("piece", "PIECE"),
                            ("kg", "KG"),
                            ("gm", "GM"),
                            ("litre", "LITRE"),
                            ("ml", "ML"),
                            ("bundle", "BUNDLE"),
                        ],
                        default="piece",
                        max_length=10,
                    ),
                ),
                ("old_price", models.IntegerField(blank=True)),
                ("price", models.IntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("sku", models.CharField(blank=True, max_length=20, null=True)),
                ("has_inventory", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "ACTIVE"),
                            ("archived", "ARCHIVED"),
                            ("draft", "DRAFT"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_variants",
                        to="ziria.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_product_variants",
                        to="ziria.store",
                    ),
                ),
            ],
            options={
                "db_table": "product_variants",
            },
        ),
    ]
