# Generated by Django 4.1.7 on 2023-04-25 17:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ziria", "0007_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("billing", "Billing"),
                            ("shipping", "Shipping"),
                            ("pick_up", "Pick Up"),
                        ],
                        max_length=10,
                    ),
                ),
                ("full_name", models.CharField(max_length=300)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("country_code", models.CharField(max_length=3)),
                ("state", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(max_length=100)),
                ("zip", models.CharField(blank=True, max_length=10, null=True)),
                ("address1", models.TextField(blank=True, null=True)),
                ("address2", models.TextField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_addresses",
                        to="ziria.customer",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_addresses",
                        to="ziria.store",
                    ),
                ),
            ],
            options={
                "db_table": "addresses",
            },
        ),
    ]
