# Generated by Django 4.1.7 on 2023-04-25 17:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ziria", "0010_orderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("amount", "Amount"), ("percentage", "Percentage")],
                        max_length=12,
                    ),
                ),
                ("discount_value", models.IntegerField()),
                (
                    "discount_allocation",
                    models.CharField(
                        choices=[
                            ("entire_order", "Entire Order"),
                            ("specific_product", "Specific Product"),
                        ],
                        max_length=20,
                    ),
                ),
                ("max_discount", models.IntegerField(blank=True, null=True)),
                ("min_order_value", models.IntegerField(blank=True, null=True)),
                ("uses_per_customer", models.IntegerField(blank=True, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("currency", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "ACTIVE"),
                            ("archived", "ARCHIVED"),
                            ("draft", "DRAFT"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("allow_multiple_discounts", models.BooleanField(default=False)),
                (
                    "store",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_discounts",
                        to="ziria.store",
                    ),
                ),
            ],
            options={
                "db_table": "discounts",
            },
        ),
    ]
