# Generated by Django 4.1.7 on 2023-04-25 17:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ziria", "0011_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("amount", "Amount"), ("percentage", "Percentage")],
                        max_length=12,
                    ),
                ),
                ("discount_value", models.IntegerField()),
                (
                    "discount_allocation",
                    models.CharField(
                        choices=[
                            ("entire_order", "Entire Order"),
                            ("specific_product", "Specific Product"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discount_order_discounts",
                        to="ziria.discount",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_item_order_discounts",
                        to="ziria.orderitem",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_order_discounts",
                        to="ziria.store",
                    ),
                ),
            ],
            options={
                "db_table": "order_discounts",
            },
        ),
    ]
