# Generated by Django 4.1.7 on 2023-04-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ziria", "0012_orderdiscount"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("purchase", "Purchase"),
                    ("refund", "refund"),
                    ("return", "return"),
                ],
                default="purchase",
                max_length=10,
            ),
        ),
    ]
