# Generated by Django 4.1.7 on 2023-05-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ziria", "0014_store_orders_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="products_count",
            field=models.IntegerField(default=0),
        ),
    ]
