# Generated by Django 4.1.7 on 2023-05-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ziria", "0015_store_products_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("archived", "Archived"),
                    ("cancelled", "Cancelled"),
                    ("draft", "Draft"),
                ],
                default="open",
                max_length=10,
            ),
        ),
    ]
