# Generated by Django 4.1.7 on 2023-05-12 18:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ziria", "0017_plugin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "events",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("order.created", "Order Created"),
                                ("order.updated", "Order Updated"),
                                ("product.created", "Product Created"),
                                ("product.updated", "Product Updated"),
                            ],
                            max_length=20,
                        ),
                        size=None,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("target_url", models.URLField()),
                (
                    "target_content_type",
                    models.CharField(
                        choices=[("json", "JSON"), ("xml", "XML")],
                        default="json",
                        max_length=5,
                    ),
                ),
                ("secret", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("plugin", "Plugin"), ("custom", "Custom")],
                        default="custom",
                        max_length=10,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhooks",
                        to="ziria.store",
                    ),
                ),
            ],
            options={
                "db_table": "webhooks",
            },
        ),
    ]
